spring.application.name=opticalmanager

#DB
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost:5555}/opticalmanager
spring.datasource.username=${DB_USERNAME:user}
spring.datasource.password=${DB_PASSWORD:password}
spring.datasource.driver-class-name=org.postgresql.Driver

# Loga no console as consultas SQL que o Hibernate está fazendo no banco
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# AI
spring.ai.vertex.ai.gemini.project-id=${PROJECT_ID}
spring.ai.vertex.ai.gemini.location=us-east4

# Doc
springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false